import type { Metadata } from "next";
import { Rubik_Vinyl } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const rubikVinyl = Rubik_Vinyl({
  variable: "--font-rubik-vinyl",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Relax With Me",
  description: "Generated by create next app",
  icons: {
    icon: "https://www.freepnglogos.com/uploads/coffee-logo-png/coffee-logo-symbol-19.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      <body className={` ${rubikVinyl.variable}  antialiased`}>
        
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
